### First endpoint
GET http://localhost:8000/users

###

### Second endpoint
GET http://localhost:8000/users/more/single/232323/123
    ?offset=20


### dto params validation
GET http://localhost:8000/users/dto/323

###
GET http://localhost:8000/users/service/123
    ?limit=20
    &page=1